# Generated by Django 5.1.2 on 2025-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
