# Generated by Django 5.1.2 on 2025-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_profile_banned_until_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated hours needed (for hourly rate jobs)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='price_type',
            field=models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Price')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
