# Generated by Django 5.1.2 on 2025-04-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_skill_estimated_hours_skill_price_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='estimated_hours',
        ),
    ]
